services:
  - type: web
    name: marcenaria-reis
    runtime: docker
    repo: https://github.com/wagnerodri/MR-com-sistema
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MAINTENANCE_MODE
        value: "false"
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
