services:
  - type: web
    name: marcenaria-reis
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MAINTENANCE_MODE
        value: "true"
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
